GYM:
    AUTO_NAME: CloseCab
    OBS_KEYS:
    - robot_head_depth
    - joint
    - ee_pos
    - is_holding
    - relative_resting_position
ENVIRONMENT:
    MAX_EPISODE_STEPS: 200
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/in_drawer_1k_100.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangeCloseDrawerTask-v0
    SETTLE_STEPS: 5
    BASE_ANGLE_NOISE: 0.15
    SPAWN_REGION_SCALE: 0.2
    JOINT_MAX_IMPULSE: -1.0

    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    CONSTRAINT_VIOLATION_DROPS_OBJECT: true
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false

    USE_MARKER_T: true
    SUCCESS_STATE: 0.0
    REWARD_MEASURE: art_obj_reward
    SUCCESS_MEASURE: art_obj_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: 0.0
    END_ON_SUCCESS: true
    EASY_INIT: false
    JOINT_SENSOR:
        TYPE: JointSensor
        DIMENSIONALITY: 7
    END_EFFECTOR_SENSOR:
        TYPE: EEPositionSensor
    IS_HOLDING_SENSOR:
        TYPE: IsHoldingSensor
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: RelativeRestingPositionSensor
    SENSORS:
    - JOINT_SENSOR
    - IS_HOLDING_SENSOR
    - END_EFFECTOR_SENSOR
    - RELATIVE_RESTING_POS_SENSOR
    ROBOT_FORCE:
        TYPE: RobotForce
        MIN_FORCE: 20.0
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: -1.0
    ART_OBJ_AT_DESIRED_STATE:
        TYPE: ArtObjAtDesiredState
        USE_ABSOLUTE_DISTANCE: true
        SUCCESS_DIST_THRESHOLD: 0.05
    ART_OBJ_SUCCESS:
        TYPE: ArtObjSuccess
        REST_DIST_THRESHOLD: 0.15
    ART_OBJ_REWARD:
        TYPE: ArtObjReward
        WRONG_GRASP_END: true
        WRONG_GRASP_PEN: 5.0
        GRASP_REWARD: 0.0
        ART_AT_DESIRED_STATE_REWARD: 5.0
        ART_DIST_REWARD: 10.0
        EE_DIST_REWARD: 1.0
        MARKER_DIST_REWARD: 1.0
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    NUM_STEPS:
        TYPE: NumStepsMeasure
    DID_VIOLATE_HOLD_CONSTRAINT:
        TYPE: DidViolateHoldConstraintMeasure
    MEASUREMENTS:
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - DOES_WANT_TERMINATE
    - EE_DIST_TO_MARKER
    - END_EFFECTOR_TO_REST_DISTANCE
    - ART_OBJ_AT_DESIRED_STATE
    - ART_OBJ_STATE
    - ART_OBJ_SUCCESS
    - ART_OBJ_REWARD
    - NUM_STEPS
    - DID_VIOLATE_HOLD_CONSTRAINT
    - BAD_CALLED_TERMINATE
    ACTIONS:
        ARM_ACTION:
            GRIP_CONTROLLER: null
            ARM_JOINT_DIMENSIONALITY: 7
    POSSIBLE_ACTIONS:
    - ARM_ACTION
    - BASE_VELOCITY
    - REARRANGE_STOP
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
    - data/objects/ycb/configs/
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: false
    ACTION_SPACE_CONFIG: v0
    AGENTS:
    - AGENT_0
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    FORWARD_STEP_SIZE: 0.25
    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
    NEEDS_MARKERS: true
    ARM_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
