GYM:
    AUTO_NAME: "NavPick"
    OBS_KEYS:
    - robot_head_depth
    - relative_resting_position
    - obj_start_sensor
    - obj_goal_sensor
    - obj_start_gps_compass
    - obj_goal_gps_compass
    - joint
    - is_holding
ENVIRONMENT:
    MAX_EPISODE_STEPS: 1000
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/train/rearrange_easy.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangeCompositeTask-v0

    REWARD_MEASURE: "move_obj_reward"
    SUCCESS_MEASURE: "composite_success"
    SUCCESS_REWARD: 100.0
    SLACK_REWARD: -0.01
    END_ON_SUCCESS: True

    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false
    CONSTRAINT_VIOLATION_ENDS_EPISODE: False
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    EASY_INIT: false
    TASK_SPEC_BASE_PATH: configs/tasks/rearrange/pddl/
    TASK_SPEC: nav_pick
    PDDL_DOMAIN_DEF: replica_cad
    SENSORS:
    - RELATIVE_RESTING_POS_SENSOR
    - TARGET_START_SENSOR
    - GOAL_SENSOR
    - JOINT_SENSOR
    - IS_HOLDING_SENSOR
    - END_EFFECTOR_SENSOR
    - TARGET_START_GPS_COMPASS_SENSOR
    - TARGET_GOAL_GPS_COMPASS_SENSOR
    - LOCALIZATION_SENSOR
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: -1.0
    ROBOT_FORCE:
        TYPE: RobotForce
        MIN_FORCE: 20.0
    MOVE_OBJECTS_REWARD:
        TYPE: MoveObjectsReward
        PICK_REWARD: 1.0
        SUCCESS_DIST: 0.15
        SINGLE_REARRANGE_REWARD: 1.0
        DIST_REWARD: 1.0
        # General Rearrange Reward config
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    MEASUREMENTS:
    - OBJECT_TO_GOAL_DISTANCE
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - END_EFFECTOR_TO_OBJECT_DISTANCE
    - DOES_WANT_TERMINATE
    - COMPOSITE_SUCCESS
    - NUM_STEPS
    - DID_VIOLATE_HOLD_CONSTRAINT
    - MOVE_OBJECTS_REWARD
    - COMPOSITE_STAGE_GOALS

    ACTIONS:
        ARM_ACTION:
            TYPE: ArmAction
            ARM_CONTROLLER: ArmRelPosAction
            GRIP_CONTROLLER: SuctionGraspAction
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: false
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
        BASE_VELOCITY:
            TYPE: BaseVelAction
            LIN_SPEED: 10.0
            ANG_SPEED: 10.0
            ALLOW_DYN_SLIDE: true
            END_ON_STOP: false
            ALLOW_BACK: true
            MIN_ABS_LIN_SPEED: 1.0
            MIN_ABS_ANG_SPEED: 1.0
        REARRANGE_STOP:
            TYPE: RearrangeStopAction
    POSSIBLE_ACTIONS:
    - ARM_ACTION
    - BASE_VELOCITY
    - REARRANGE_STOP
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - "data/objects/ycb/configs/"
    ACTION_SPACE_CONFIG: v0
    GRASP_IMPULSE: 1000.0
    HOLD_THRESH: 0.09
    AC_FREQ_RATIO: 4
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: true
    AGENTS:
    - AGENT_0
    CONCUR_RENDER: true
    AUTO_SLEEP: true
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: false
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        START_POSITION:
        - 0
        - 0
        - 0
        START_ROTATION:
        - 0
        - 0
        - 0
        - 1
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: true
        WIDTH: 128
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
