# Config for empty task to explore the scene.
ENVIRONMENT:
    MAX_EPISODE_STEPS: 0
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    TYPE: RearrangeEmptyTask-v0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    DESIRED_RESTING_POSITION: [0.5, 0.0, 1.0]

    # Reach task config
    RENDER_TARGET: True
    EE_SAMPLE_FACTOR: 0.8

    # In radians
    BASE_ANGLE_NOISE: 0.0
    BASE_NOISE: 0.0
    CONSTRAINT_VIOLATION_ENDS_EPISODE: False

    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False
    FORCE_REGENERATE: True

    TARGET_START_SENSOR:
        TYPE: "TargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    GOAL_SENSOR:
        TYPE: "GoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_TARGET_START_SENSOR:
        TYPE: "AbsTargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_GOAL_SENSOR:
        TYPE: "AbsGoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    END_EFFECTOR_SENSOR:
        TYPE: "EEPositionSensor"
    IS_HOLDING_SENSOR:
        TYPE: "IsHoldingSensor"
    SENSORS: ["JOINT_SENSOR"]

    ########################
    # General measures
    FORCE_TERMINATE:
        TYPE: "ForceTerminate"
        MAX_ACCUM_FORCE: -1.0
    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    ROBOT_COLLS:
      TYPE: "RobotCollisions"
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance"

    ########################
    # Pick specific measurements
    PICK_REWARD:
        TYPE: "RearrangePickReward"
        DIST_REWARD: 20.0
        SUCC_REWARD: 10.0
        PICK_REWARD: 20.0
        CONSTRAINT_VIOLATE_PEN: 10.0
        DROP_PEN: 5.0
        WRONG_PICK_PEN: 5.0
        COLL_PEN: 1.0
        ROBOT_OBJ_COLL_PEN: 0.0
        MAX_ACCUM_FORCE: 5000.0

        FORCE_PEN: 0.001
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
        USE_DIFF: True

        DROP_OBJ_SHOULD_END: False
        WRONG_PICK_SHOULD_END: False
    PICK_SUCCESS:
        TYPE: "RearrangePickSuccess"
        EE_RESTING_SUCCESS_THRESHOLD: 0.15
    ########################


    MEASUREMENTS:
        # General measure
        - "ROBOT_FORCE"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
        BASE_VELOCITY:
            TYPE: "BaseVelAction"
            LIN_SPEED: 10.0
            ANG_SPEED: 10.0
            ALLOW_DYN_SLIDE: True
            END_ON_STOP: False
            ALLOW_BACK: True
            MIN_ABS_LIN_SPEED: 1.0
            MIN_ABS_ANG_SPEED: 1.0
        EMPTY:
            TYPE: "EmptyAction"
    POSSIBLE_ACTIONS:
        - ARM_ACTION
        - BASE_VELOCITY
        - EMPTY

SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - "data/objects/ycb/configs/"
    ACTION_SPACE_CONFIG: v0
    GRASP_IMPULSE: 1000.0
    HOLD_THRESH: 0.09
    AC_FREQ_RATIO: 4
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: True
    AGENTS: ['AGENT_0']

    AGENT_0:
        IS_SET_START_STATE: False
        RADIUS: 0.3
        SENSORS: ['HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'ARM_RGB_SENSOR', 'ARM_DEPTH_SENSOR']
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
        ROBOT_TYPE: "FetchRobot"
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
        WIDTH: 128
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
